name: 'Assembly Differ'
description: 'Compare and Diff assemblies from different sources'
inputs:
  args:
    description: 'Assembly Differ arguments'
    required: true
    default: '-h'
  assembly-differ-binaries:
    description: 'Binaries folder of assembly-differ'
    required: true
    default: ${{github.workspace}}
runs:
  using: 'node12'
  main: 'index.js'